#!/usr/bin/env bash
# Script that display information about subdomains using awk and function
# shellcheck disable=SC2086
Add_subd () {
if [ "$2" ];
then
    echo -n "The subdomain $2 is a"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print " " $4 " record and points to " $5}' | tail -n 1
else
    for i in www lb-01 web-01 web-02
    do
        echo -n "The subdomain $i is a"
        dig "$i.$1" | grep -A1 'ANSWER SECTION:' | awk '{print " " $4 " record and points to " $5}' | tail -n 1
    done
fi
}
Add_subd "$1" "$2"
