#!/usr/bin/env bash
#onfigure your Nginx server so that /redirect_me is redirecting to another page
sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
