#!/usr/bin/env bash
#create a file PID, do a infinte loop, displays signals
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"
trap "echo 'I hate the kill command'; sudo rm -f /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'; exit" SIGINT
trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
while (true)
    do
    echo "To infinity and beyond"
    sleep 2
done
