#!/usr/bin/env bash
#script that reads the content of a directory

filedir="/etc/passwd"

while IFS= read -r line
do
    username=$(echo "$line" | cut -d':' -f1)
	id=$(echo "$line" | cut -d':' -f3)
	directory=$(echo "$line" | cut -d':' -f7)

    echo "$username:$id:$directory"
done < "$filedir"
