#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd, using the while loop + IFS.

filedir="/etc/passwd"

while IFS=: read -r username pass u_id g_id u_info home cmd
do
	echo "The user $username is part of the $g_id gang, lives in $home and rides $cmd. $u_id's place is protected by the passcode $pass, more info about the user here: $u_info"
done < "$filedir"
