#!/usr/bin/env bash
#script that print 12 hours of the day with minutes
i=0

while [ $i -lt 13 ]
do
    echo "Hour: $i"
    j=1
    while [ $j -lt 60 ]
    do
        echo "$j"
        j=$((j+1))
    done

    i=$((i+1))
done
