#!/usr/bin/env bash
# configure other default user fixing the port listen to 8080
pkill -9 apache2
chmod 777 /etc/nginx/nginx.conf
sudo sed -i '2i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
